- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    # StationWare edit start
    jumpsuit: SWClothingUniformJumpsuitPlayer
    # StationWare edit end
    ears: ClothingHeadsetGrey
  # StationWare edit start
  innerclothingskirt: SWClothingUniformJumpskirtPlayer
  # StationWare edit end

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
